import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";
import { unaVezPorClave } from "../lib/una-vez";

let conexion: { url: string; sql: ReturnType<typeof postgres> } | null = null;

function getClient(url: string) {
  // Un DATABASE_URL distinto apunta a otra base, así que el cliente anterior
  // deja de servir: se reemplaza y se cierra el pool que quedó atrás.
  if (conexion?.url !== url) {
    const anterior = conexion;
    conexion = {
      url,
      sql: postgres(url, {
        prepare: false,
        max: 1,
        connect_timeout: 10,
        idle_timeout: 20,
      }),
    };
    void anterior?.sql.end({ timeout: 5 }).catch(() => {});
  }
  return conexion.sql;
}

const prepararEsquema = unaVezPorClave(async (url: string) => {
  const sql = getClient(url);
  const statements = [
    `CREATE TABLE IF NOT EXISTS cubicles (
      id INTEGER PRIMARY KEY,
      brand_model TEXT NOT NULL DEFAULT '',
      serial_number TEXT NOT NULL DEFAULT '',
      inventory_code TEXT NOT NULL DEFAULT '',
      admin_pin_status TEXT NOT NULL DEFAULT 'unreviewed',
      student_pin_status TEXT NOT NULL DEFAULT 'unreviewed',
      admin_pin_encrypted TEXT NOT NULL DEFAULT '',
      student_pin_encrypted TEXT NOT NULL DEFAULT '',
      internet_type TEXT NOT NULL DEFAULT 'unreviewed',
      outlet_status TEXT NOT NULL DEFAULT 'unreviewed',
      keyboard TEXT NOT NULL DEFAULT 'Sin registrar',
      mouse TEXT NOT NULL DEFAULT 'Sin registrar',
      ip TEXT NOT NULL DEFAULT '',
      mac TEXT NOT NULL DEFAULT '',
      observations TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      updated_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS checklist_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      label TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS checklist_results (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cubicle_id INTEGER NOT NULL REFERENCES cubicles(id) ON DELETE CASCADE,
      item_id INTEGER NOT NULL REFERENCES checklist_items(id) ON DELETE CASCADE,
      checked BOOLEAN NOT NULL DEFAULT FALSE
    )`,
    `CREATE TABLE IF NOT EXISTS station_tasks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cubicle_id INTEGER NOT NULL REFERENCES cubicles(id) ON DELETE CASCADE,
      description TEXT NOT NULL,
      completed BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS app_metadata (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )`,
    "CREATE UNIQUE INDEX IF NOT EXISTS result_cubicle_item_idx ON checklist_results (cubicle_id, item_id)",
    "CREATE INDEX IF NOT EXISTS task_cubicle_idx ON station_tasks (cubicle_id)",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS inventory_code TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS admin_pin_status TEXT NOT NULL DEFAULT 'unreviewed'",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS student_pin_status TEXT NOT NULL DEFAULT 'unreviewed'",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS admin_pin_encrypted TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS student_pin_encrypted TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS internet_type TEXT NOT NULL DEFAULT 'unreviewed'",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS outlet_status TEXT NOT NULL DEFAULT 'unreviewed'",
    "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS mac TEXT NOT NULL DEFAULT ''",
    `CREATE TABLE IF NOT EXISTS net_racks (
      id TEXT PRIMARY KEY,
      nombre TEXT NOT NULL DEFAULT '',
      ubicacion TEXT NOT NULL DEFAULT '',
      x INTEGER NOT NULL DEFAULT 0,
      y INTEGER NOT NULL DEFAULT 0,
      w INTEGER NOT NULL DEFAULT 0,
      h INTEGER NOT NULL DEFAULT 0,
      notas TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS net_equipos (
      id TEXT PRIMARY KEY,
      rack TEXT NOT NULL DEFAULT '',
      tipo TEXT NOT NULL DEFAULT 'switch',
      etiqueta TEXT NOT NULL DEFAULT '',
      modelo TEXT NOT NULL DEFAULT '',
      puertos INTEGER NOT NULL DEFAULT 0,
      color TEXT NOT NULL DEFAULT '',
      x INTEGER NOT NULL DEFAULT 0,
      y INTEGER NOT NULL DEFAULT 0,
      nota TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS net_puertos (
      id TEXT PRIMARY KEY,
      equipo TEXT NOT NULL,
      n INTEGER NOT NULL,
      estado TEXT NOT NULL DEFAULT 'libre',
      nota TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS net_espacios (
      id TEXT PRIMARY KEY,
      nombre TEXT NOT NULL DEFAULT '',
      ubicacion TEXT NOT NULL DEFAULT '',
      categoria TEXT NOT NULL DEFAULT 'sala',
      estado TEXT NOT NULL DEFAULT 'sin-verificar',
      x INTEGER NOT NULL DEFAULT 0,
      y INTEGER NOT NULL DEFAULT 0,
      nota TEXT NOT NULL DEFAULT ''
    )`,
    "ALTER TABLE net_espacios ADD COLUMN IF NOT EXISTS ubicacion TEXT NOT NULL DEFAULT ''",
    `CREATE TABLE IF NOT EXISTS net_enlaces (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      a TEXT NOT NULL,
      b TEXT NOT NULL,
      tipo TEXT NOT NULL DEFAULT 'patch',
      nota TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS net_bitacora (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      fecha TEXT NOT NULL,
      tipo TEXT NOT NULL,
      objetivo TEXT NOT NULL DEFAULT '',
      antes TEXT NOT NULL DEFAULT '',
      despues TEXT NOT NULL DEFAULT '',
      nota TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS net_orden (
      id TEXT PRIMARY KEY,
      orden INTEGER NOT NULL
    )`,
    "CREATE INDEX IF NOT EXISTS net_puerto_equipo_idx ON net_puertos (equipo)",
    "CREATE UNIQUE INDEX IF NOT EXISTS net_enlace_par_idx ON net_enlaces (a, b)",
    "CREATE INDEX IF NOT EXISTS net_enlace_a_idx ON net_enlaces (a)",
    "CREATE INDEX IF NOT EXISTS net_enlace_b_idx ON net_enlaces (b)",
    "CREATE INDEX IF NOT EXISTS net_bitacora_objetivo_idx ON net_bitacora (objetivo)",
  ];
  for (const statement of statements) await sql.unsafe(statement);

  const now = new Date().toISOString();
  const defaultModel = "Lenovo IdeaCentre AIO 310-20IAP (Type F0CL)";
  await sql`
    INSERT INTO cubicles (id, brand_model, updated_at)
    SELECT station_id, ${defaultModel}, ${now}
    FROM generate_series(1, 40) AS station_id
    ON CONFLICT (id) DO NOTHING
  `;
  await sql`
    UPDATE cubicles
    SET brand_model = ${defaultModel}
    WHERE brand_model = '' AND status != 'no_computer'
  `;

  const count = await sql`SELECT COUNT(*) AS total FROM checklist_items`;
  if (!Number(count[0]?.total ?? 0)) {
    const defaults = ["Enciende correctamente", "Acceso a internet", "Audio operativo", "Pantalla sin daños"];
    for (const label of defaults) {
      await sql`INSERT INTO checklist_items (label, created_at) VALUES (${label}, ${now})`;
    }
  }
});

export async function getDb() {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) throw new Error("Falta configurar DATABASE_URL con la conexión de Supabase.");
  // Supabase is migrated separately in production. Running DDL during every
  // serverless cold start can leave concurrent requests waiting on table locks.
  if (!process.env.VERCEL) await prepararEsquema(url);
  return drizzle(getClient(url), { schema });
}
