import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";

let initialized: Promise<void> | null = null;
let client: ReturnType<typeof postgres> | null = null;

function getClient() {
  if (client) return client;

  const connectionString = process.env.DATABASE_URL?.trim();
  if (!connectionString) throw new Error("Falta configurar DATABASE_URL con la conexión de Supabase.");

  client = postgres(connectionString, {
    prepare: false,
    max: 1,
    connect_timeout: 10,
    idle_timeout: 20,
  });
  return client;
}

async function ensureSchema() {
  if (initialized) return initialized;
  initialized = (async () => {
    const sql = getClient();
    const statements = [
      `CREATE TABLE IF NOT EXISTS cubicles (
        id INTEGER PRIMARY KEY,
        brand_model TEXT NOT NULL DEFAULT '',
        serial_number TEXT NOT NULL DEFAULT '',
        inventory_code TEXT NOT NULL DEFAULT '',
        admin_pin_status TEXT NOT NULL DEFAULT 'unreviewed',
        student_pin_status TEXT NOT NULL DEFAULT 'unreviewed',
        admin_pin_encrypted TEXT NOT NULL DEFAULT '',
        student_pin_encrypted TEXT NOT NULL DEFAULT '',
        internet_type TEXT NOT NULL DEFAULT 'unreviewed',
        outlet_status TEXT NOT NULL DEFAULT 'unreviewed',
        keyboard TEXT NOT NULL DEFAULT 'Sin registrar',
        mouse TEXT NOT NULL DEFAULT 'Sin registrar',
        ip TEXT NOT NULL DEFAULT '',
        mac TEXT NOT NULL DEFAULT '',
        observations TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'pending',
        updated_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS checklist_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label TEXT NOT NULL,
        created_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS checklist_results (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cubicle_id INTEGER NOT NULL,
        item_id INTEGER NOT NULL,
        checked BOOLEAN NOT NULL DEFAULT FALSE
      )`,
      `CREATE TABLE IF NOT EXISTS station_tasks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cubicle_id INTEGER NOT NULL,
        description TEXT NOT NULL,
        completed BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS app_metadata (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      )`,
      "CREATE UNIQUE INDEX IF NOT EXISTS result_cubicle_item_idx ON checklist_results (cubicle_id, item_id)",
      "CREATE INDEX IF NOT EXISTS task_cubicle_idx ON station_tasks (cubicle_id)",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS inventory_code TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS admin_pin_status TEXT NOT NULL DEFAULT 'unreviewed'",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS student_pin_status TEXT NOT NULL DEFAULT 'unreviewed'",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS admin_pin_encrypted TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS student_pin_encrypted TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS internet_type TEXT NOT NULL DEFAULT 'unreviewed'",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS outlet_status TEXT NOT NULL DEFAULT 'unreviewed'",
      "ALTER TABLE cubicles ADD COLUMN IF NOT EXISTS mac TEXT NOT NULL DEFAULT ''",
    ];
    for (const statement of statements) await sql.unsafe(statement);

    const now = new Date().toISOString();
    const defaultModel = "Lenovo IdeaCentre AIO 310-20IAP (Type F0CL)";
    await sql`
      INSERT INTO cubicles (id, brand_model, updated_at)
      SELECT station_id, ${defaultModel}, ${now}
      FROM generate_series(1, 40) AS station_id
      ON CONFLICT (id) DO NOTHING
    `;
    await sql`
      UPDATE cubicles
      SET brand_model = ${defaultModel}
      WHERE brand_model = '' AND status != 'no_computer'
    `;

    const count = await sql`SELECT COUNT(*) AS total FROM checklist_items`;
    if (!Number(count[0]?.total ?? 0)) {
      const defaults = ["Enciende correctamente", "Acceso a internet", "Audio operativo", "Pantalla sin daños"];
      for (const label of defaults) {
        await sql`INSERT INTO checklist_items (label, created_at) VALUES (${label}, ${now})`;
      }
    }
  })();
  return initialized;
}

export async function getDb() {
  // Supabase is migrated separately in production. Running DDL during every
  // serverless cold start can leave concurrent requests waiting on table locks.
  if (!process.env.VERCEL) await ensureSchema();
  return drizzle(getClient(), { schema });
}
