-- Tablas del encendido programado. Se aplican con instalar-wol.sh y tambien
-- viven en el DDL de db/index.ts, para que un clon limpio las cree solo.
CREATE TABLE IF NOT EXISTS wol_programas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL DEFAULT '',
  -- Dias ISO como digitos sueltos: '12345' = lunes a viernes, 1=lunes, 7=domingo.
  dias TEXT NOT NULL DEFAULT '',
  -- 'HH:MM' en la hora local del servidor.
  hora TEXT NOT NULL DEFAULT '',
  -- 'todos' o una lista de cubiculos: '3,7,12'.
  objetivo TEXT NOT NULL DEFAULT 'todos',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS wol_eventos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- NULL = envio manual, no lo disparo ningun programa.
  programa INTEGER,
  cubiculo INTEGER NOT NULL,
  mac TEXT NOT NULL DEFAULT '',
  -- enviado | ya-encendido | sin-mac
  resultado TEXT NOT NULL DEFAULT 'enviado',
  enviado_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  verificado_at TIMESTAMPTZ,
  desperto BOOLEAN
);

CREATE INDEX IF NOT EXISTS wol_evento_cubiculo_idx ON wol_eventos (cubiculo, enviado_at DESC);
-- La verificacion busca justamente esto en cada corrida del timer.
CREATE INDEX IF NOT EXISTS wol_evento_pendiente_idx ON wol_eventos (enviado_at) WHERE verificado_at IS NULL;
